//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zyan.Communication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zyan.Communication.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked..
        /// </summary>
        internal static string AccountLockedException_DefaultMessage {
            get {
                return ResourceManager.GetString("AccountLockedException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown username or bad password..
        /// </summary>
        internal static string AccountNotFoundException_DefaultMessage {
            get {
                return ResourceManager.GetString("AccountNotFoundException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple module controlers per module are not allowed..
        /// </summary>
        internal static string ApplicationException_MultipleModuleControlersNotAllowed {
            get {
                return ResourceManager.GetString("ApplicationException_MultipleModuleControlersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channel was created..
        /// </summary>
        internal static string ApplicationException_NoChannel {
            get {
                return ResourceManager.GetString("ApplicationException_NoChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Remoting Channel was created..
        /// </summary>
        internal static string ApplicationException_NoChannelCreated {
            get {
                return ResourceManager.GetString("ApplicationException_NoChannelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channel factory method specified..
        /// </summary>
        internal static string ApplicationException_NoChannelFactorySpecified {
            get {
                return ResourceManager.GetString("ApplicationException_NoChannelFactorySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No formatter specified..
        /// </summary>
        internal static string ApplicationException_NoFormatterSpecified {
            get {
                return ResourceManager.GetString("ApplicationException_NoFormatterSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server component is registered for the interface {0} at the server {1}..
        /// </summary>
        internal static string ApplicationException_NoServerComponentIsRegisteredForTheGivenInterface {
            get {
                return ResourceManager.GetString("ApplicationException_NoServerComponentIsRegisteredForTheGivenInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification service is not running on the host..
        /// </summary>
        internal static string ApplicationException_NotificationServiceNotRunning {
            get {
                return ResourceManager.GetString("ApplicationException_NotificationServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type &apos;{0}&apos; is not an interface. Transparent proxy creation requires an interface type..
        /// </summary>
        internal static string ApplicationException_SpecifiedTypeIsNotAnInterface {
            get {
                return ResourceManager.GetString("ApplicationException_SpecifiedTypeIsNotAnInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not delegate: {0}..
        /// </summary>
        internal static string ApplicationException_TypeIsNotDelegate {
            get {
                return ResourceManager.GetString("ApplicationException_TypeIsNotDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must not be empty..
        /// </summary>
        internal static string ArgumentException_AddressMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentException_AddressMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component host name missing..
        /// </summary>
        internal static string ArgumentException_ComponentHostNameMissing {
            get {
                return ResourceManager.GetString("ArgumentException_ComponentHostNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty session ID is not allowed..
        /// </summary>
        internal static string ArgumentException_EmptySessionIDIsNotAllowed {
            get {
                return ResourceManager.GetString("ArgumentException_EmptySessionIDIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate to factory method missing..
        /// </summary>
        internal static string ArgumentException_FactoryMethodDelegateMissing {
            get {
                return ResourceManager.GetString("ArgumentException_FactoryMethodDelegateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface name missing..
        /// </summary>
        internal static string ArgumentException_InterfaceNameMissing {
            get {
                return ResourceManager.GetString("ArgumentException_InterfaceNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration setting: {0}.
        /// </summary>
        internal static string ArgumentException_InvalidConfigSetting {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidConfigSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration setting: &apos;{0}&apos;..
        /// </summary>
        internal static string ArgumentException_InvalidConfigurationSetting {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidConfigurationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &apos;connectionAgeLimit&apos; must be 0 or greater..
        /// </summary>
        internal static string ArgumentException_InvalidConnectionAgeLimitSetting {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidConnectionAgeLimitSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &apos;sweepFrequency&apos; must be 0 or greater..
        /// </summary>
        internal static string ArgumentException_InvalidSweepFrequencySetting {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidSweepFrequencySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;maxRetries&apos; must be 1 or greater..
        /// </summary>
        internal static string ArgumentException_MaxAttempts {
            get {
                return ResourceManager.GetString("ArgumentException_MaxAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name missing..
        /// </summary>
        internal static string ArgumentException_MethodNameMissing {
            get {
                return ResourceManager.GetString("ArgumentException_MethodNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outpit pin property name missing..
        /// </summary>
        internal static string ArgumentException_OutPutPinNameMissing {
            get {
                return ResourceManager.GetString("ArgumentException_OutPutPinNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL is invalid. Use the FormatUrl method of the client protocol setup class to create a valid URL for the selected protocol..
        /// </summary>
        internal static string ArgumentException_ServerUrlIsInvalid {
            get {
                return ResourceManager.GetString("ArgumentException_ServerUrlIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL is missing..
        /// </summary>
        internal static string ArgumentException_ServerUrlMissing {
            get {
                return ResourceManager.GetString("ArgumentException_ServerUrlMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For type &apos;{0}&apos; is already a serialization handler registered..
        /// </summary>
        internal static string ArgumentException_TypeHasAlreadyAHandler {
            get {
                return ResourceManager.GetString("ArgumentException_TypeHasAlreadyAHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided implementation type is not a class..
        /// </summary>
        internal static string ArgumentException_TypeIsNotAClass {
            get {
                return ResourceManager.GetString("ArgumentException_TypeIsNotAClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided interface type is not a interface..
        /// </summary>
        internal static string ArgumentException_TypeIsNotAInterface {
            get {
                return ResourceManager.GetString("ArgumentException_TypeIsNotAInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified encryption algorithm &apos;{0}&apos; is not supported. Use one of the following algorithms: &apos;3DES&apos;, &apos;DES&apos;, &apos;RIJNDAEL&apos; or &apos;RC2&apos;..
        /// </summary>
        internal static string ArgumentException_UnsupportedEncryptionAlgorithm {
            get {
                return ResourceManager.GetString("ArgumentException_UnsupportedEncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP port must be set within the range 0-65535 liegen..
        /// </summary>
        internal static string ArgumentOutOfRangeException_InvalidHttpPortRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_InvalidHttpPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TCP port must be set within the range 0-65535 liegen..
        /// </summary>
        internal static string ArgumentOutOfRangeException_InvalidTcpPortRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_InvalidTcpPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connection info missing..
        /// </summary>
        internal static string CryptoRemotingException_ClientConnectionInfoMissing {
            get {
                return ResourceManager.GetString("CryptoRemotingException_ClientConnectionInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client request: {0}..
        /// </summary>
        internal static string CryptoRemotingException_InvalidClientRequest {
            get {
                return ResourceManager.GetString("CryptoRemotingException_InvalidClientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid secure transaction ID. May be caused by timeout..
        /// </summary>
        internal static string CryptoRemotingException_InvalidTransactionID {
            get {
                return ResourceManager.GetString("CryptoRemotingException_InvalidTransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Vector from server missing..
        /// </summary>
        internal static string CryptoRemotingException_IVMissing {
            get {
                return ResourceManager.GetString("CryptoRemotingException_IVMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key changed since the message was encrypted..
        /// </summary>
        internal static string CryptoRemotingException_KeyChanged {
            get {
                return ResourceManager.GetString("CryptoRemotingException_KeyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key missing..
        /// </summary>
        internal static string CryptoRemotingException_PublicKeyNotFound {
            get {
                return ResourceManager.GetString("CryptoRemotingException_PublicKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server requires encrypted connection for this client..
        /// </summary>
        internal static string CryptoRemotingException_ServerRequiresEncryption {
            get {
                return ResourceManager.GetString("CryptoRemotingException_ServerRequiresEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public key transmitted..
        /// </summary>
        internal static string CryptoRemotingException_SharedKeyMissing {
            get {
                return ResourceManager.GetString("CryptoRemotingException_SharedKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format for &apos;address&apos; parameter: {0}.
        /// </summary>
        internal static string Format_Exception_InvalidAddressFormat {
            get {
                return ResourceManager.GetString("Format_Exception_InvalidAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID &apos;{0}&apos; is invalid. Please log on first..
        /// </summary>
        internal static string InvalidSessionException_SessionIDInvalid {
            get {
                return ResourceManager.GetString("InvalidSessionException_SessionIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find component for interface &apos;{0}&apos;..
        /// </summary>
        internal static string KeyNotFoundException_CannotFindComponentForInterface {
            get {
                return ResourceManager.GetString("KeyNotFoundException_CannotFindComponentForInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No serialization handler is registered for type &apos;{0}&apos;..
        /// </summary>
        internal static string KeyNotFoundException_SerializationHandlerNotFound {
            get {
                return ResourceManager.GetString("KeyNotFoundException_SerializationHandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not found: &apos;{0}&apos;..
        /// </summary>
        internal static string MissingMethodException_MethodNotFound {
            get {
                return ResourceManager.GetString("MissingMethodException_MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is expired..
        /// </summary>
        internal static string PasswordExpiredException_DefaultMessage {
            get {
                return ResourceManager.GetString("PasswordExpiredException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting remote host: {0}..
        /// </summary>
        internal static string RemotingException_ConnectionError {
            get {
                return ResourceManager.GetString("RemotingException_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving channel information from remote host..
        /// </summary>
        internal static string RemotingException_ErrorReceivingChannelInfo {
            get {
                return ResourceManager.GetString("RemotingException_ErrorReceivingChannelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending channel information to remote host..
        /// </summary>
        internal static string RemotingException_ErrorSendingChannelInfo {
            get {
                return ResourceManager.GetString("RemotingException_ErrorSendingChannelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message sink set..
        /// </summary>
        internal static string RemotingException_MessageSinkNotSet {
            get {
                return ResourceManager.GetString("RemotingException_MessageSinkNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No remote address specified for reconnect..
        /// </summary>
        internal static string RemotingException_NoAddressForReconnect {
            get {
                return ResourceManager.GetString("RemotingException_NoAddressForReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context information is missing..
        /// </summary>
        internal static string SecurityException_ContextInfoMissing {
            get {
                return ResourceManager.GetString("SecurityException_ContextInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials missing..
        /// </summary>
        internal static string SecurityException_CredentialsMissing {
            get {
                return ResourceManager.GetString("SecurityException_CredentialsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password missing..
        /// </summary>
        internal static string SecurityException_PasswordMissing {
            get {
                return ResourceManager.GetString("SecurityException_PasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name missing..
        /// </summary>
        internal static string SecurityException_UserNameMissing {
            get {
                return ResourceManager.GetString("SecurityException_UserNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows security token credential missing..
        /// </summary>
        internal static string SecurityException_WindowsTokenMissing {
            get {
                return ResourceManager.GetString("SecurityException_WindowsTokenMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to server &apos;{0}&apos;..
        /// </summary>
        internal static string SocketException_LostConnectionToServer {
            get {
                return ResourceManager.GetString("SocketException_LostConnectionToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authenticated by operating system..
        /// </summary>
        internal static string UserNotAuthenicatedByWindows {
            get {
                return ResourceManager.GetString("UserNotAuthenicatedByWindows", resourceCulture);
            }
        }
    }
}
